/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JF_Interface;

import banco_cliente.Conectar_Sockets;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.AbstractButton;

/**
 *
 * @author Danilo
 */
public class JF_Administrar_Cuentas extends javax.swing.JFrame {

    /**
     * Creates new form JF_Administrar_Cuentas
     */
    public JF_Administrar_Cuentas() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_admin_cuentas = new javax.swing.ButtonGroup();
        jR_cuenta_crear = new javax.swing.JRadioButton();
        jR_cuenta_borrar = new javax.swing.JRadioButton();
        jR_cuenta_modificar = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jT_cuenta_numero = new javax.swing.JTextField();
        jT_cuenta_Propietario_nom = new javax.swing.JTextField();
        jT_cuenta_Propietario_ape = new javax.swing.JTextField();
        jT_cuenta_dinero = new javax.swing.JTextField();
        jB_guardar = new javax.swing.JButton();
        jB_cancelar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg_admin_cuentas.add(jR_cuenta_crear);
        jR_cuenta_crear.setSelected(true);
        jR_cuenta_crear.setText("Crear cuenta ");
        jR_cuenta_crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jR_cuenta_crearActionPerformed(evt);
            }
        });

        bg_admin_cuentas.add(jR_cuenta_borrar);
        jR_cuenta_borrar.setText("Borrar cuenta ");
        jR_cuenta_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jR_cuenta_borrarActionPerformed(evt);
            }
        });

        bg_admin_cuentas.add(jR_cuenta_modificar);
        jR_cuenta_modificar.setText("Modificar cuenta");
        jR_cuenta_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jR_cuenta_modificarActionPerformed(evt);
            }
        });

        jLabel1.setText("Número de la Cuenta ");

        jLabel2.setText("Propietario de la cuenta");

        jLabel3.setText("Dinero ingresado ");

        jB_guardar.setText("Guardar");
        jB_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_guardarActionPerformed(evt);
            }
        });

        jB_cancelar.setText("Cancelar");
        jB_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_cancelarActionPerformed(evt);
            }
        });

        jLabel4.setText("Nombre Propietario");

        jLabel5.setText("Apellido Propietario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jR_cuenta_crear)
                        .addGap(18, 18, 18)
                        .addComponent(jR_cuenta_borrar)
                        .addGap(18, 18, 18)
                        .addComponent(jR_cuenta_modificar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(50, 50, 50)
                                .addComponent(jT_cuenta_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(75, 75, 75)
                                    .addComponent(jB_guardar)
                                    .addGap(18, 18, 18)
                                    .addComponent(jB_cancelar)
                                    .addGap(78, 78, 78))
                                .addComponent(jLabel3))))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jT_cuenta_Propietario_nom)
                            .addComponent(jT_cuenta_Propietario_ape, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                            .addComponent(jT_cuenta_dinero))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jR_cuenta_crear)
                    .addComponent(jR_cuenta_modificar)
                    .addComponent(jR_cuenta_borrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jT_cuenta_numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jT_cuenta_Propietario_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jT_cuenta_Propietario_ape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jT_cuenta_dinero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_guardar)
                    .addComponent(jB_cancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jR_cuenta_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jR_cuenta_borrarActionPerformed
        jT_cuenta_numero.setText("");
        jT_cuenta_Propietario_nom.setText("");
        jT_cuenta_dinero.setText("");
    }//GEN-LAST:event_jR_cuenta_borrarActionPerformed

    private void jR_cuenta_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jR_cuenta_modificarActionPerformed
        jT_cuenta_numero.setText("");
        jT_cuenta_Propietario_nom.setText("");
        jT_cuenta_dinero.setText("");
    }//GEN-LAST:event_jR_cuenta_modificarActionPerformed

    private void jR_cuenta_crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jR_cuenta_crearActionPerformed
        jT_cuenta_numero.setText("");
        jT_cuenta_Propietario_nom.setText("");
        jT_cuenta_dinero.setText("");
    }//GEN-LAST:event_jR_cuenta_crearActionPerformed

    private void jB_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_cancelarActionPerformed

        //Limpiar campos
        jT_cuenta_numero.setText("");
        jT_cuenta_Propietario_nom.setText("");
        jT_cuenta_dinero.setText("");
        
        JF_Banco jfb = new JF_Banco();
        jfb.show();
        dispose();

    }//GEN-LAST:event_jB_cancelarActionPerformed

    private void jB_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_guardarActionPerformed

        String Operacion;

        if (jR_cuenta_crear.isSelected()) {
            Operacion = "crear";
        } else if (jR_cuenta_borrar.isSelected()) {
            Operacion = "borrar";
        } else {
            Operacion = "modificar";

        }

        String value
                = "1,"
                + Operacion  + ","
                + jT_cuenta_numero.getText() + ","
                + jT_cuenta_Propietario_nom.getText() + ","
                + jT_cuenta_Propietario_ape.getText() + ","
                + jT_cuenta_dinero.getText();

        Conectar_Sockets cs = new Conectar_Sockets();

        cs.Datos(value);
    }//GEN-LAST:event_jB_guardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_Administrar_Cuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_Administrar_Cuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_Administrar_Cuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_Administrar_Cuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_Administrar_Cuentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg_admin_cuentas;
    private javax.swing.JButton jB_cancelar;
    private javax.swing.JButton jB_guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jR_cuenta_borrar;
    private javax.swing.JRadioButton jR_cuenta_crear;
    private javax.swing.JRadioButton jR_cuenta_modificar;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jT_cuenta_Propietario_ape;
    private javax.swing.JTextField jT_cuenta_Propietario_nom;
    private javax.swing.JTextField jT_cuenta_dinero;
    private javax.swing.JTextField jT_cuenta_numero;
    // End of variables declaration//GEN-END:variables
}
